// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_svgplot
void rcpp_svgplot(Rcpp::DataFrame dat, std::string filename);
RcppExport SEXP _svgplotr_rcpp_svgplot(SEXP datSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dat(datSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_svgplot(dat, filename);
    return R_NilValue;
END_RCPP
}
