# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_svgplot
#' @noRd
rcpp_svgplot <- function(dat, filename) {
    invisible(.Call(`_svgplotr_rcpp_svgplot`, dat, filename))
}

