# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_svgplot_lines
#' @noRd
rcpp_svgplot_lines <- function(dat, filename, html) {
    invisible(.Call(`_svgplotr_rcpp_svgplot_lines`, dat, filename, html))
}

#' rcpp_svgplot_points
#' @noRd
rcpp_svgplot_points <- function(dat, filename, html) {
    invisible(.Call(`_svgplotr_rcpp_svgplot_points`, dat, filename, html))
}

